---
title: "Tablero Acciones"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(quantmod)
library(tidyverse)
library(plotly)
library(dplyr)

# Vector con acciones que descargare
Tikets <- c("NFLX", "AAPL")
# Api para descargar acciones desde Yahoo
serie <- getSymbols(Tikets, src = "yahoo", auto.assign = TRUE,from = "2015-01-01")

# Almacenar datos con los que trabajare
datos <- data.frame(NFLX$NFLX.Close, AAPL$AAPL.Close)

#Transformar el indice en una columna llamada Fecha
datos <- datos %>% rownames_to_column(var = "Fecha")

#Dar formato fecha a los datos que estaban en tipo caracter de la columna Fecha 
datos$Fecha <- as.Date(datos$Fecha)

datos$Año <- format(datos$Fecha, "%Y")

```

## Column {.sidebar}

```{r}
# Crear inputs con el nombre de las acciones

selectInput("A", label = "Acción",
            choices = c("NFLX.Close", "AAPL.Close"), selected = " ")



```

## Row

### Gráfico

```{r}
# Acceder a un valor del imput destinado para las acciones

serie <- reactive({
  datos[,input$A]
}) 


#renderPrint({
 # serie() # parentesis porque es reactivo
  
#})

# Graficar las acciones con Render
renderPlotly({
 ggplot(datos, aes(x = Fecha, y = serie(), color = Año)) + 
  geom_line(linewidth = 0.4) +
    labs(x = "Año", y = "Valor Acción (USD)") +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
    theme_bw()+
    guides(color ="none")+ #color=FALSE
    theme(panel.grid.major = element_line(color = "gray"))
  })



```

## Row

### Estadisticas descriptivas

```{r}
renderPrint({
  media <- mean(serie())
  desv <- sd(serie())
  cat("Media: ", media, "\n")
  cat("Desviación estándar: ", desv, "\n")
})


```

<style>
pre {
  font-size: 18px;
}
</style>

### Diagrama de Caja

```{r} 
renderPlotly({
ggplot(datos, aes(y = serie())) +
    geom_boxplot(fill="#69b3a2") +
    labs(y ="USD") 
    #ylab("USD")
  
  #boxplot(serie())
})

```
